# Flik Server - Blue/Green Deployment
services:
  # Flik Application - Blue
  flik-blue:
    profiles:
      - blue
    build:
      context: .
      dockerfile: Dockerfile
    image: flik-springboot:latest
    container_name: flik-blue
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SERVER_PORT=8080
      - JAVA_OPTS=-Xms256m -Xmx1g -XX:+UseG1GC -XX:MaxGCPauseMillis=200
      - BUILD_INFO=${BUILD_TAG:-latest}
      - DEPLOYMENT_ENV=blue
      - KAKAO_API_KEY=${KAKAO_API_KEY}
      - NAVER_SECRET=${NAVER_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_MASTER_KEY=${ADMIN_MASTER_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8083:8080"
    networks:
      - goormthon-java_dormung-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s          # 30s → 15s (더 자주 체크)
      timeout: 20s           # 10s → 20s (타임아웃 증가)
      retries: 5             # 3 → 5 (재시도 증가)
      start_period: 90s      # 60s → 90s (시작 대기 시간 증가)


  # Flik Application - Green
  flik-green:
    profiles:
      - green
    build:
      context: .
      dockerfile: Dockerfile
    image: flik-springboot:latest
    container_name: flik-green
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SERVER_PORT=8080
      - JAVA_OPTS=-Xms256m -Xmx1g -XX:+UseG1GC -XX:MaxGCPauseMillis=200
      - BUILD_INFO=${BUILD_TAG:-latest}
      - DEPLOYMENT_ENV=green
      - KAKAO_API_KEY=${KAKAO_API_KEY}
      - NAVER_SECRET=${NAVER_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_MASTER_KEY=${ADMIN_MASTER_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8084:8080"
    networks:
      - goormthon-java_dormung-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s          # 30s → 15s (더 자주 체크)
      timeout: 20s           # 10s → 20s (타임아웃 증가)
      retries: 5             # 3 → 5 (재시도 증가)
      start_period: 90s      # 60s → 90s (시작 대기 시간 증가)


networks:
  goormthon-java_dormung-network:
    external: true