spring:
  application:
    name: flik

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  frontend:
    url: ${FRONTEND_URL}

server:
  port: 8080
  servlet:
      context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    groups-order: desc
  api-docs:
    path: /v3/api-docs

security:
  swagger-bypass:
    enabled: true

# Actuator endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info,beans,env
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
    info:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}
  health:
    redis:
      enabled: true
    db:
      enabled: true
    diskspace:
      enabled: true

# Logging configuration
logging:
  level:
    root: INFO
    yunrry.flik: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

kakao:
  api:
    key: ${KAKAO_API_KEY:your-kakao-api-key}

naver:
  api:
    client-id: iR0esJl2LAiYkZGwXukQ
    client-secret: ${NAVER_SECRET:your-naver-api-key}


oauth2:
  providers:
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/api/auth/oauth/callback/google}
      authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
      token-uri: https://oauth2.googleapis.com/token
      user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
      scope: openid email profile
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET}
      redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/api/auth/oauth/callback/kakao}
      authorization-uri: https://kauth.kakao.com/oauth/authorize
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me
      scope: profile_nickname profile_image account_email

jwt:
  secret: ${JWT_SECRET:your-secret-key-here-must-be-at-least-256-bits}
  access-token-expiry: 36000    # 10시간
  refresh-token-expiry: 604800 # 7일

rate-limit:
  login:
    max-attempts: 5
    lock-duration: 15m

#
admin:
  master-key: ${ADMIN_MASTER_KEY:ADMIN_MASTER_KEY}