spring:
  application:
    name: flik
  
  profiles:
    active: local
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080


# Actuator endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info,beans,env
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
    info:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}
  health:
    redis:
      enabled: true
    db:
      enabled: true
    diskspace:
      enabled: true

# Logging configuration
logging:
  level:
    root: INFO
    yunrry.flik: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"